version: '2'
services:
  app:
    build: ./project/
    image: rango-app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    command: /srv/initapp.sh
    ## compose on windows can't run command from shell script
    # command:
    #   - gunicorn
    #   - config.wsgi:application
    #   - --name
    #   - "rango_app"
    #   - --bind
    #   - "0.0.0.0:8000"
    #   - --workers
    #   - "3"
    #   - --log-level
    #   - "debug"
    #   # - --log-file
    #   # - "./logs/gunicorn.log"
    #   # - --access-logfile
    #   # - "./logs/access.log"
    #   - --reload
    volumes:
      - /srv/static_root
      - /srv/media_root
    expose:
      - "8000"
    depends_on:
      - db
  db:
    build: ./db/
    image: rango-db
  nginx:
    build: ./nginx/
    image: rango-nginx
    ports:
      - "8000:80"
    volumes_from:
      - app
